title: "Our Year with Rieke"
description: "A scrapbook of memories from our exchange year"
baseurl: "/rieke"
url: "https://worthingtonjg.github.io"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "pink"

author:
  name: "Jonathan & Family"
  bio: "Sharing a magical year with our exchange student Rieke 💗"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
